name: 'Terraform'
on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]  # Runs when a PR targets the main branch  

jobs:
  terraform:
    name: 'Terraform'
    env:
      # AWS secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '0.14.3'

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform with variable
      - name: Terraform Plan
        run: terraform plan -var="instance_type=t2.micro"

      # Apply Terraform with variable
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="instance_type=t2.micro"
